export interface User{
    id ?: number,
    firstName: string,
    surname : string,
    mat : string,
    date : Date | null,
    street : string,
    neigh : string,
    cep:string,
    number:string,
    course : string,
    description : string,
    phone : string,
    cpf : string,
    gender : string,
    email : string,
    password : string,
}